.\" Author Ben Lavery
.\" Contact the author: ben.lavery@gmail.com
.\" Created on 29/05/2010
.\" Last edited on 30/05/2010
.\" Revision 3
.\" 
.\" LICENCE:
.\" This is licensed under the Creative Commons Licence.
.\" To view the human-readable summary of this licence, please direct your browser to:
.\" http://creativecommons.org/licenses/by-sa/2.0/uk/
.\" For the full licence, direct your browser to:
.\" http://creativecommons.org/licenses/by-sa/2.0/uk/legalcode
.\"
.\" Format this file with
.\" groff -man -Tascii gallery.1
.\" Generate PS file with
.\" groff -t -e -mandoc -Tps gallery.1 > gallery.ps
.\" Generate HTML file with
.\" groff -man -Tascii gallery.1 | man2html -title '<Gallery>' > gallery.html
.\"
.TH GALLERY 1 "MAY 2010" "UNIX" "User Manuals"
.SH NAME
gallery \- Generates a gallery of images.
.SH SYNOPSIS
.BR gallery " [-" ChHqTV "] [-" l " | -" L "] [-" "B big_image_size_in_pixels" "] [-" "c number_of_columns" "] [-" "D description_location" "] [-" "e extension" "] [-" "H html_version" "] [-" "t title" "] [-" "r relative_to" "] [-" "S small_image_size_in_pixels" "] [-" "s source_directory" "] -" "d directory"
.SH DESCRIPTION
The
.B gallery
command will generate a gallery of images.  Pass it a directory full of images and it will resize them and format an HTML file to display the images.  From revision 47 you can pass it a source directory and it will copy the contents of the directory to the directory specified under the -d option.

The script creates two directories in the directory passed to it:
.I bigs
which stores the larger images for the gallery (longest edge is 640px) and
.I thumbs
which contain thumbnails of the images (longest edge is 128px).  The script uses
.BR sips (1)
in OS X to do the image manipulation and a combination of
.BR convert "(1) and " identify (1)
in other UNIX environments.

After resizing, the script formats a file called
.IB index. EXTENSION
.RI ( index.php
by default).

The script uses some specific CSS
.I id
and
.I class
attributes.  These attributes are as follows:
.IP "id='gallery-body'"
This is a div that encompasses the entire gallery
.IP "class='gallery-column'"
This is a div which encompasses a
.B ROW
of images.  By default there are four images per 'gallery-column', but the user may specify otherwise.  This is placed inside the 'gallery-body' div.
.IP "class='gallery-image'"
This is a div that encompasses a single image and is placed inside the 'gallery-column' div.
.IP "class='gallery-caption'"
This is a paragraph which includes the caption text of your image.  This is placed inside the 'gallery-image' div, underneath the image.

.SH OPTIONS
.IP "-B big_image_size_in_pixels"
The size of the main images.  The number is applied to the longest side and is measured in pixels.
.IP "-c number of columns"
Number of columns per row.  Default is four.
.IP "-C"
Use captions \- These are generated using the file names without the file extension.
.IP "-d directory"
Absolute link to directory with images in.  Escape spaces with a \ symbol.
.IP "-D description_location"
Add the description found in
.I description.txt
which should be located in the directory specified with -d.
.IP -e
Extension for the gallery file.  Default is php.
.IP -h
Displays help text.
.IP "-H html_version"
Create a standalone HTML page.  Specify HTML4.01, XHTML101, or XHTML1.1 to make the script generate a standalone, standards compliant page.
IP -l
Add the "rel" tag to all of the links to use LightBox for displaying images.
.IP -L
Add the "rel" tag to all of the links to use LightBox groups for displaying images. The group name is based on the gallery title, so this option should only be used with -t "title" or -T. 
.IP -q
Be quiet.  Suppress all output.  By default the script is very willing to give information about what it is doing.
.IP "-r relative directory"
Directory to that the links should be relative to.  Escape spaces with a \e symbol.
.IP "-s source directory"
Use this directory as a source for images.  Images will be copied from here into the directory
.IP "-S small_image_size_in_pixels"
The size of the thumbnail images.  The number is applied to the longest side and is measured in pixels.
.IP "-t title"
Title of the gallery.  Quote when using spaces.
.IP -T
Generate a title for the gallery based on directory name.
.IP -V
Prints the version (revision) number.
.SH EXAMPLES
.IP "gallery -h"
Displays help text.

.IP "gallery -d /tmp/example"
Script assumes that
.I /tmp/example
is a directory full of images.  These images will be manipulated to the right size and placed into folders.  An index page will be created with HTML markup for displaying the images.

.IP "gallery -r /tmp/mySite -d /tmp/mySite/gallery/example"
This will generate a gallery with images that are relative to 
.I /tmp/mySite.

For example:
.I <a href='mySite/gallery/example/IMG_9313.JPG'>...

.IP "gallery -s ~/Photos/Album/My\e Web\e Album -d /web/mySite/gallery/example"
This will copy all of the images from
.I ~/Photos/Album/My\e Web\e Album
to the
.I /web/mySite/gallery/example
directory.  It will then process the script as usual.  This option still works with the -r option.

.IP "gallery -t \(dqMy Gallery\(dq -d /tmp/example"
Will give the gallery the title 
.B My Gallery.

.IP "gallery -T -d /tmp/example"
The gallery will get the title 
.B example.

.IP "gallery -LT -d /tmp/example"
The gallery will get the title 
.B example
and will be grouped for viewing with LightBox using the same title.  For example: 
.B <a href='example/IMG_9317.JPG' rel='lightbox[example]'>

.IP "gallery -e \(dqhtml\(dq -d /tmp/example"
Will create the file
.IR /tmp/example/index.html .
The default is index.php.

.IP "gallery -c 5 -d /tmp/example"
Will create a gallery with five columns.

.IP "gallery -Tl -r /Users/benlavery/Sites/hashbang0 -d /Users/benlavery/Sites/hashbang0/gallery/My\e Holiday"
This is an example of the command I use for creating galleries for my own site.  Notice how spaces in the path are escaped with a \e.
.SH BUGS
No bugs that I know of!  Please report any bugs to author!
.SH AUTHOR
Ben Lavery <ben.lavery@gmail.com>
.SH "SEE ALSO"
.BR sips (1),
.BR convert (1),
.BR identify (1),